from typing import Any, AsyncGenerator
from collections.abc import AsyncIterable
from agent_framework import CheckpointStorage, Content,AgentResponseUpdate, Agent,InMemoryCheckpointStorage,WorkflowCheckpoint, WorkflowEvent
from agent_framework.exceptions import AgentFrameworkException
from agent_framework.orchestrations import HandoffBuilder,HandoffAgentUserRequest
from agent_framework.openai import OpenAIChatCompletionClient
from app.agents.azure_chat.account_agent import AccountAgent
from app.agents.azure_chat.transaction_agent import TransactionHistoryAgent
from app.agents.azure_chat.payment_agent import PaymentAgent
from app.helpers.no_history_provider import NoHistoryProvider
from uuid import uuid4
import logging

logger = logging.getLogger(__name__)

class HandoffOrchestrator:
    
    triage_instructions = """
      You are a banking customer support agent triaging customer requests about their banking account, movements, payments.
      You have to evaluate the whole conversation with the customer and handoff to AccountAgent, TransactionHistoryAgent, PaymentAgent. 
      When delegation is required, call the matching handoff too based on triage rules.
      
      
      # Triage rules
      - If the user request is related to bank account information like account balance, payment methods, cards and beneficiaries book you must call handoff_to_AccountAgent.
      - If the user request is related to banking movements and payments history, you must call handoff_to_TransactionHistoryAgent.
      - If the user request is related to initiate a payment request, upload a bill or invoice image for payment or manage an on-going payment process, you must call handoff_to_PaymentAgent.
      - If the user request is not related to account, transactions or payments you must respond to the user that you are not able to help with the request.

      
    """

    """ A simple in-memory store [workflow_id/thread_id, WorkflowCheckpoint] to keep track of threads per user/session.
     Thread_id and workflow_id are synonymous in this context. We are keeping the thread_id concept and assign it the workflow_id value generated by the agent framework.
    In production, this should be replaced with a persistent store like a database or distributed cache.
    """
    thread_checkpoint_store: dict[str, CheckpointStorage] = {}

    def __init__(self, 
                 azure_chat_client: OpenAIChatCompletionClient,
                 account_agent: AccountAgent,
                 transaction_agent: TransactionHistoryAgent,
                 payment_agent: PaymentAgent
                                ):
      self.azure_chat_client = azure_chat_client
      self.account_agent = account_agent
      self.transaction_agent = transaction_agent
      self.payment_agent = payment_agent
      self.workflow = None  # Will be initialized in async method

    async def initialize(self, checkpoint_storage: CheckpointStorage ):
      """Initialize the workflow with async operations"""
      triage_agent = Agent(
            client=self.azure_chat_client,
            instructions=HandoffOrchestrator.triage_instructions,
            name="triage_agent",
            # NoHistoryProvider prevents the framework from auto-injecting an
            # InMemoryHistoryProvider.  Inside a HandoffBuilder workflow the
            # executor already tracks the full conversation, so the auto-injected
            # provider would duplicate messages on every turn, eventually causing
            # OpenAI 400 errors due to mismatched tool_calls / tool results.
            context_providers=[NoHistoryProvider()]
        )
      
      self.workflow = (
        HandoffBuilder(
            name="banking_assistant_handoff",
            participants=[triage_agent, 
                          await self.account_agent.build_af_agent(),
                          await self.transaction_agent.build_af_agent(),
                          await self.payment_agent.build_af_agent()],
            termination_condition=lambda conv: sum(1 for msg in conv if msg.role == "user") >= 20,
            checkpoint_storage=checkpoint_storage,
        )
        .with_start_agent(triage_agent)
        .build()
    )

            
    async def _get_or_create_checkpoint_store(self,thread_id: str) -> CheckpointStorage :
        checkpoint_storage = HandoffOrchestrator.thread_checkpoint_store.get(thread_id, None)
        if checkpoint_storage is not None:
            return checkpoint_storage
        
        logger.info(f"Creating new checkpoint storage for thread_id: {thread_id}")
        checkpoint_storage = InMemoryCheckpointStorage()
        HandoffOrchestrator.thread_checkpoint_store[thread_id] = checkpoint_storage
        return checkpoint_storage

    
    async def _resume_workflow_with_response(self, checkpoint_storage: CheckpointStorage, checkpoint_id: str, user_message: str) -> AsyncIterable[WorkflowEvent]:
        """Resume a workflow from a checkpoint with a response to a RequestInfoEvent.

        Args:
            checkpoint (WorkflowCheckpoint): The checkpoint to resume from.
            response (dict[str, str]): The response mapping request IDs to user inputs.

        Yields:
            AsyncIterable[WorkflowEvent]: The events generated by resuming the workflow.
        """
        events = self.workflow.run(checkpoint_id=checkpoint_id,    #type: ignore
                                    checkpoint_storage=checkpoint_storage, 
                                    stream=True) 
        
        responses: dict[str, object] = {}
        
        #We need to collect all workflow events otherwise we get concurrent workflow execution error when trying to resume.
        consumed_events = [event async for event in events]
        for event in consumed_events:
            if event.type == "request_info":
                if isinstance(event.data, HandoffAgentUserRequest):
                        responses[event.request_id] = HandoffAgentUserRequest.create_response(user_message)
                        return self.workflow.run(responses=responses, checkpoint_id=checkpoint_id, #type: ignore
                                                 checkpoint_storage=checkpoint_storage, 
                                                 stream=True) 
                else:
                    raise AgentFrameworkException(f"RequestInfoEvent [{event.request_id}] found in the checkpoint [{checkpoint_id}] that is not a HandoffAgentUserRequest.")
        #if we reach here, something went wrong. For this use case HandoffOrchestrator expected to always trigger a RequestInfoEvent.
        raise AgentFrameworkException(f"No RequestInfoEvent found in the checkpoint [{checkpoint_id}]")
            
    
    async def processMessageStream(self, user_message: str , thread_id : str ) -> AsyncGenerator[WorkflowEvent,None]:
        
        checkpoint_storage = await self._get_or_create_checkpoint_store(thread_id)
       
        #Agents are initialized asynchronously due to the use of MCP tools. So we can't initialize the workflow in __init__. We do it lazily here.
        if self.workflow is None:
                await self.initialize(checkpoint_storage)
              
        checkpoint = None
        events = None

        # try to retrieve checkpoint for the given thread_id. If None, we start a new conversation.
        checkpoint = await checkpoint_storage.get_latest(workflow_name=self.workflow.name) # type: ignore
        workflow_id = self.workflow.id  # type: ignore

        if checkpoint is None:
            # Start a new conversation. This is the first user message.
            async for event in self.workflow.run(user_message, stream=True):# type: ignore
                yield event # type: ignore
        else:
            #Resuming an existing conversation.
            async for event in await self._resume_workflow_with_response(checkpoint_storage,
                                                                         checkpoint.checkpoint_id, 
                                                                         user_message):
                yield event


    async def processToolApprovalResponse(self, thread_id: str, approved:bool, call_id: str, request_id: str, tool_name: str) -> AsyncGenerator[WorkflowEvent,None]:
        """Process a tool approval response from the user.

        Args:
            thread_id (str): The thread ID associated with the workflow.
            approved (bool): Whether the user approved the tool execution.

        """
        checkpoint_storage = await self._get_or_create_checkpoint_store(thread_id)

        if self.workflow is None:
               await self.initialize(checkpoint_storage)
       

        checkpoint = await checkpoint_storage.get_latest(workflow_name=self.workflow.name) # type: ignore
        if checkpoint is None:
            raise AgentFrameworkException(f"No checkpoint found for thread_id: {thread_id} when trying to process tool approval response")
        
        events = self.workflow.run(checkpoint_id=checkpoint.checkpoint_id, #type: ignore
                                   checkpoint_storage=checkpoint_storage, stream=True) #type: ignore
        
        responses: dict[str, object] = {}
        #restart the workflow to get the reference to FunctionApprovalRequestEvent
        consumed_events = [event async for event in events]
        for event in consumed_events:
            yield event
            if event.type == "request_info":
                if isinstance(event.data, Content) and event.data.type == "function_approval_request":
                        responses[event.request_id] = event.data.to_function_approval_response(approved=approved)
                        async for event in self.workflow.run(responses=responses, #type: ignore
                                                             checkpoint_id=checkpoint.checkpoint_id, 
                                                             checkpoint_storage=checkpoint_storage, stream=True) : #type: ignore
                            yield event
                else:
                    raise AgentFrameworkException(f"RequestInfoEvent [{event.request_id}] found in the checkpoint [{checkpoint.checkpoint_id}] that is not a HandoffUserInputRequest.")
        